using System;
using System.Collections.Generic;
using System.Linq;

namespace ADRIFT
{
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On;
Option Explicit On;


Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _;
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _;
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _;
internal class Resources
    {

        private static Global.System.Resources.ResourceManager resourceMan;

        private static Global.System.Globalization.CultureInfo resourceCulture;

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _;
        internal void New()
        {
            MyBase.New;
        }

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _;
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager;
            {
                get
                {
                if (Object.ReferenceEquals(resourceMan, null))
                {
                    private Global.System.Resources.ResourceManager temp = new Global.System.Resources.ResourceManager("ADRIFT.Resources", GetType(Resources).Assembly);
                    resourceMan = temp
                }
                return resourceMan;
            }
        }

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _;
        internal static Global.System.Globalization.CultureInfo Culture { get; set; }
            {
                get
                {
                return resourceCulture;
            }
                }
                set
                {
                resourceCulture = value
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Adrift() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("Adrift", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgAdd16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgAdd16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgALR16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgALR16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgALR32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgALR32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgArrangeHorz16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgArrangeHorz16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgArrangeVert16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgArrangeVert16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgAxes32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgAxes32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgBold() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgBold", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCancel16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCancel16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCancel32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCancel32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCascade16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCascade16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCentre16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCentre16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCentre32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCentre32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCharacter16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCharacter16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCharacter32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCharacter32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgChildren() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgChildren", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgColour() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgColour", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCopy() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCopy", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgCut() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgCut", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgDelete() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgDelete", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgDelete32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgDelete32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgDeveloper24() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgDeveloper24", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgEdit16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgEdit16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgEvent16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgEvent16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgEvent32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgEvent32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgExport16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgExport16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgExport32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgExport32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgExpression() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgExpression", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFilter() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFilter", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFind() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFind", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFindNext() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFindNext", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFolder16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFolder16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFolderBlue16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFolderBlue16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFolderClosed16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFolderClosed16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFolderClosedBlue16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFolderClosedBlue16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFolderList32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFolderList32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFont() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFont", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFontColour() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFontColour", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFunction16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFunction16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgFunction32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgFunction32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgGrid16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgGrid16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgGroup16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgGroup16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgGroup32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgGroup32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgHelp16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgHelp16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgHint16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgHint16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgHint32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgHint32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgImport16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgImport16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgImport32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgImport32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgIn48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgIn48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgInfo16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgInfo16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgItalic() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgItalic", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgKey16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgKey16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgLeft() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgLeft", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgLocation16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgLocation16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgLocation32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgLocation32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgLock32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgLock32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgMap16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgMap16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgMap32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgMap32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgNew16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgNew16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgNew32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgNew32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgObjectDynamic16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgObjectDynamic16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgObjectDynamic32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgObjectDynamic32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgObjectStatic16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgObjectStatic16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgObjectStatic32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgObjectStatic32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOneToOne() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOneToOne", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOpen() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOpen", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOpen16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOpen16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOpen32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOpen32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOptions16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOptions16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOptions32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOptions32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgOut48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgOut48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgParent() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgParent", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPaste() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPaste", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPause48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPause48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPauseShadow48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPauseShadow48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPicture() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPicture", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPlanView16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPlanView16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPlanView32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPlanView32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPlay48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPlay48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPlayer16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPlayer16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPlayShadow48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPlayShadow48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPrint16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPrint16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgPrint32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgPrint32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgProperty16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgProperty16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgProperty32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgProperty32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgRefresh16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgRefresh16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgReplace16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgReplace16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgRight() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgRight", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgRun16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgRun16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgRun32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgRun32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSave16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSave16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSave32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSave32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSaveAs32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSaveAs32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSettings16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSettings16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSettings32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSettings32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSpelling() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSpelling", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgStop48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgStop48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgStopShadow48() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgStopShadow48", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSynonym16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSynonym16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgSynonym32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgSynonym32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTaskGeneral16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTaskGeneral16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTaskGeneral32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTaskGeneral32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTaskSpecific16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTaskSpecific16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTaskSpecific32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTaskSpecific32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTaskSystem16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTaskSystem16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTaskSystem32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTaskSystem32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTile16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTile16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgTimeEvent16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgTimeEvent16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgUnlock32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgUnlock32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgVariable16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgVariable16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgVariable32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgVariable32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgWarn16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgWarn16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgWarn32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgWarn32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgWeb() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgWeb", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgZoomIn16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgZoomIn16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgZoomIn32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgZoomIn32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgZoomOut16() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgZoomOut16", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property imgZoomOut32() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("imgZoomOut32", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property LYDIAN() As Byte();
            {
                get
                {
                private object obj = ResourceManager.GetObject("LYDIAN", resourceCulture);
                return CType(obj,Byte());
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property OpenSelectedItemHS() As System.Drawing.Bitmap;
            {
                get
                {
                private object obj = ResourceManager.GetObject("OpenSelectedItemHS", resourceCulture);
                return CType(obj,System.Drawing.Bitmap);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property player() As System.Drawing.Icon;
            {
                get
                {
                private object obj = ResourceManager.GetObject("player", resourceCulture);
                return CType(obj,System.Drawing.Icon);
            }
        }

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property taf() As System.Drawing.Icon;
            {
                get
                {
                private object obj = ResourceManager.GetObject("taf", resourceCulture);
                return CType(obj,System.Drawing.Icon);
            }
        }
    }
}

}