using System;
using System.Collections.Generic;
using System.Linq;

namespace ADRIFT
{
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On;
Option Explicit On;


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _;
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _;
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _;
    Partial Friend NotInheritable Class MySettings;
        Inherits Global.System.Configuration.ApplicationSettingsBase;

        private static MySettings defaultInstance = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(new MySettings()),MySettings);

#Region "My.Settings Auto-Save Functionality"
#if _MyType = "WindowsForms"
    private static bool addedHandler;

    private static New Object addedHandlerLockObject;

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _;
    private static void AutoSaveSettings(Global.System.Object sender, Global.System.EventArgs e)
    {
        if (My.Application.SaveMySettingsOnExit)
        {
            My.Settings.Save();
        }
    }
#endif
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            {
                get
                {

#if _MyType = "WindowsForms"
               if (Not addedHandler)
               {
                    SyncLock addedHandlerLockObject;
                        if (Not addedHandler)
                        {
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings;
                            addedHandler = True
                        }
                    End SyncLock
                }
#endif
                return defaultInstance;
            }
        }
    }
}

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _;
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _;
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _;
    internal static class MySettingsProperty
    {

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _;
        internal Global.ADRIFT.My.MySettings Settings { get; }
            {
                get
                {
                return Global.ADRIFT.My.MySettings.Default;
            }
        }
    }
}

}