using System;
using System.Collections.Generic;
using System.Linq;
using System.Xml.Serialization;

namespace ADRIFT
{
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

' xsd trizbort.xsd /classes /language:vb

Option Strict On;
Option Explicit On;


'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _;
 System.SerializableAttribute(),  _;
 System.Diagnostics.DebuggerStepThroughAttribute(),  _;
 System.ComponentModel.DesignerCategoryAttribute("code"),  _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true),  _;
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=false)>  _;
Partial Public Class trizbort;

    private trizbortInfo infoField;

    Private mapField() As Object

    private trizbortSettings settingsField;

    '''<remarks/>
    public trizbortInfo info { get; set; }
        {
            get
            {
            return Me.infoField;
        }
            }
            set
            {
            Me.infoField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("line", GetType(trizbortLine), IsNullable:=false),  _;
     System.Xml.Serialization.XmlArrayItemAttribute("room", GetType(trizbortRoom), IsNullable:=false)>  _;
    public object[] map { get; set; }
        {
            get
            {
            return Me.mapField;
        }
            }
            set
            {
            Me.mapField = value;
        }
    }

    '''<remarks/>
    public trizbortSettings settings { get; set; }
        {
            get
            {
            return Me.settingsField;
        }
            }
            set
            {
            Me.settingsField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _;
 System.SerializableAttribute(),  _;
 System.Diagnostics.DebuggerStepThroughAttribute(),  _;
 System.ComponentModel.DesignerCategoryAttribute("code"),  _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _;
Partial Public Class trizbortInfo;

    private string titleField;

    private string authorField;

    private string descriptionField;

    '''<remarks/>
    public string title { get; set; }
        {
            get
            {
            return Me.titleField;
        }
            }
            set
            {
            Me.titleField = value;
        }
    }

    '''<remarks/>
    public string author { get; set; }
        {
            get
            {
            return Me.authorField;
        }
            }
            set
            {
            Me.authorField = value;
        }
    }

    '''<remarks/>
    public string description { get; set; }
        {
            get
            {
            return Me.descriptionField;
        }
            }
            set
            {
            Me.descriptionField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _;
 System.SerializableAttribute(),  _;
 System.Diagnostics.DebuggerStepThroughAttribute(),  _;
 System.ComponentModel.DesignerCategoryAttribute("code"),  _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)>  _;
Partial Public Class trizbortLine;

    Private dockField() As trizbortLineDock

    Private textField() As String

    private int idField;

    private bool idFieldSpecified;

    private string styleField;

    private string flowField;

    private string startTextField;

    private string endTextField;

    private string nameField;

    private int xField;

    private bool xFieldSpecified;

    private int yField;

    private bool yFieldSpecified;

    private int wField;

    private bool wFieldSpecified;

    private int hField;

    private bool hFieldSpecified;

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("dock")> _;
    public trizbortLineDock[] dock { get; set; }
        {
            get
            {
            return Me.dockField;
        }
set(trizbortLineDock())
            Me.dockField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _;
    public string[] Text { get; set; }
        {
            get
            {
            return Me.textField;
        }
set(String())
            Me.textField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int id { get; set; }
        {
            get
            {
            return Me.idField;
        }
set(Integer)
            Me.idField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool idSpecified { get; set; }
        {
            get
            {
            return Me.idFieldSpecified;
        }
set(Boolean)
            Me.idFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string style { get; set; }
        {
            get
            {
            return Me.styleField;
        }
set(String)
            Me.styleField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string flow { get; set; }
        {
            get
            {
            return Me.flowField;
        }
set(String)
            Me.flowField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string startText { get; set; }
        {
            get
            {
            return Me.startTextField;
        }
set(String)
            Me.startTextField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string endText { get; set; }
        {
            get
            {
            return Me.endTextField;
        }
set(String)
            Me.endTextField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string name { get; set; }
        {
            get
            {
            return Me.nameField;
        }
set(String)
            Me.nameField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int x { get; set; }
        {
            get
            {
            return Me.xField;
        }
set(Integer)
            Me.xField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool xSpecified { get; set; }
        {
            get
            {
            return Me.xFieldSpecified;
        }
set(Boolean)
            Me.xFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int y { get; set; }
        {
            get
            {
            return Me.yField;
        }
set(Integer)
            Me.yField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool ySpecified { get; set; }
        {
            get
            {
            return Me.yFieldSpecified;
        }
set(Boolean)
            Me.yFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int w { get; set; }
        {
            get
            {
            return Me.wField;
        }
set(Integer)
            Me.wField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool wSpecified { get; set; }
        {
            get
            {
            return Me.wFieldSpecified;
        }
set(Boolean)
            Me.wFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int h { get; set; }
        {
            get
            {
            return Me.hField;
        }
set(Integer)
            Me.hField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool hSpecified { get; set; }
        {
            get
            {
            return Me.hFieldSpecified;
        }
set(Boolean)
            Me.hFieldSpecified = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortLineDock;

    private int indexField;

    private bool indexFieldSpecified;

    private int idField;

    private bool idFieldSpecified;

    private string portField;

    private string valueField;

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int index { get; set; }
        {
            get
            {
            return Me.indexField;
        }
set(Integer)
            Me.indexField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool indexSpecified { get; set; }
        {
            get
            {
            return Me.indexFieldSpecified;
        }
set(Boolean)
            Me.indexFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int id { get; set; }
        {
            get
            {
            return Me.idField;
        }
set(Integer)
            Me.idField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool idSpecified { get; set; }
        {
            get
            {
            return Me.idFieldSpecified;
        }
set(Boolean)
            Me.idFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string port { get; set; }
        {
            get
            {
            return Me.portField;
        }
set(String)
            Me.portField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _;
    public string Value { get; set; }
        {
            get
            {
            return Me.valueField;
        }
set(String)
            Me.valueField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortRoom;

    private string objectsField;

    private int idField;

    private bool idFieldSpecified;

    private string nameField;

    private int xField;

    private bool xFieldSpecified;

    private int yField;

    private bool yFieldSpecified;

    private int wField;

    private bool wFieldSpecified;

    private int hField;

    private bool hFieldSpecified;

    private string descriptionField;

    '''<remarks/>
    public string objects { get; set; }
        {
            get
            {
            return Me.objectsField;
        }
set(String)
            Me.objectsField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int id { get; set; }
        {
            get
            {
            return Me.idField;
        }
set(Integer)
            Me.idField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool idSpecified { get; set; }
        {
            get
            {
            return Me.idFieldSpecified;
        }
set(Boolean)
            Me.idFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string name { get; set; }
        {
            get
            {
            return Me.nameField;
        }
set(String)
            Me.nameField = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int x { get; set; }
        {
            get
            {
            return Me.xField;
        }
set(Integer)
            Me.xField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool xSpecified { get; set; }
        {
            get
            {
            return Me.xFieldSpecified;
        }
set(Boolean)
            Me.xFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int y { get; set; }
        {
            get
            {
            return Me.yField;
        }
set(Integer)
            Me.yField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool ySpecified { get; set; }
        {
            get
            {
            return Me.yFieldSpecified;
        }
set(Boolean)
            Me.yFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int w { get; set; }
        {
            get
            {
            return Me.wField;
        }
set(Integer)
            Me.wField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool wSpecified { get; set; }
        {
            get
            {
            return Me.wFieldSpecified;
        }
set(Boolean)
            Me.wFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int h { get; set; }
        {
            get
            {
            return Me.hField;
        }
set(Integer)
            Me.hField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool hSpecified { get; set; }
        {
            get
            {
            return Me.hFieldSpecified;
        }
set(Boolean)
            Me.hFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public string description { get; set; }
        {
            get
            {
            return Me.descriptionField;
        }
set(String)
            Me.descriptionField = value;
        }
    }

}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettings;

    private trizbortSettingsColors colorsField;

    private trizbortSettingsFonts fontsField;

    private trizbortSettingsGrid gridField;

    private trizbortSettingsLines linesField;

    private trizbortSettingsRooms roomsField;

    private trizbortSettingsUI uiField;

    '''<remarks/>
    public trizbortSettingsColors colors { get; set; }
        {
            get
            {
            return Me.colorsField;
        }
set(trizbortSettingsColors)
            Me.colorsField = value;
        }
    }

    '''<remarks/>
    public trizbortSettingsFonts fonts { get; set; }
        {
            get
            {
            return Me.fontsField;
        }
set(trizbortSettingsFonts)
            Me.fontsField = value;
        }
    }

    '''<remarks/>
    public trizbortSettingsGrid grid { get; set; }
        {
            get
            {
            return Me.gridField;
        }
set(trizbortSettingsGrid)
            Me.gridField = value;
        }
    }

    '''<remarks/>
    public trizbortSettingsLines lines { get; set; }
        {
            get
            {
            return Me.linesField;
        }
set(trizbortSettingsLines)
            Me.linesField = value;
        }
    }

    '''<remarks/>
    public trizbortSettingsRooms rooms { get; set; }
        {
            get
            {
            return Me.roomsField;
        }
set(trizbortSettingsRooms)
            Me.roomsField = value;
        }
    }

    '''<remarks/>
    public trizbortSettingsUI ui { get; set; }
        {
            get
            {
            return Me.uiField;
        }
set(trizbortSettingsUI)
            Me.uiField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsColors;

    private string canvasField;

    private string fillField;

    private string borderField;

    private string lineField;

    private string selectedLineField;

    private string hoverLineField;

    private string largeTextField;

    private string smallTextField;

    private string lineTextField;

    private string gridField;

    '''<remarks/>
    public string canvas { get; set; }
        {
            get
            {
            return Me.canvasField;
        }
set(String)
            Me.canvasField = value;
        }
    }

    '''<remarks/>
    public string fill { get; set; }
        {
            get
            {
            return Me.fillField;
        }
set(String)
            Me.fillField = value;
        }
    }

    '''<remarks/>
    public string border { get; set; }
        {
            get
            {
            return Me.borderField;
        }
set(String)
            Me.borderField = value;
        }
    }

    '''<remarks/>
    public string line { get; set; }
        {
            get
            {
            return Me.lineField;
        }
set(String)
            Me.lineField = value;
        }
    }

    '''<remarks/>
    public string selectedLine { get; set; }
        {
            get
            {
            return Me.selectedLineField;
        }
set(String)
            Me.selectedLineField = value;
        }
    }

    '''<remarks/>
    public string hoverLine { get; set; }
        {
            get
            {
            return Me.hoverLineField;
        }
set(String)
            Me.hoverLineField = value;
        }
    }

    '''<remarks/>
    public string largeText { get; set; }
        {
            get
            {
            return Me.largeTextField;
        }
set(String)
            Me.largeTextField = value;
        }
    }

    '''<remarks/>
    public string smallText { get; set; }
        {
            get
            {
            return Me.smallTextField;
        }
set(String)
            Me.smallTextField = value;
        }
    }

    '''<remarks/>
    public string lineText { get; set; }
        {
            get
            {
            return Me.lineTextField;
        }
set(String)
            Me.lineTextField = value;
        }
    }

    '''<remarks/>
    public string grid { get; set; }
        {
            get
            {
            return Me.gridField;
        }
set(String)
            Me.gridField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsFonts;

    private trizbortSettingsFontsRoom roomField;

    private trizbortSettingsFontsObject objectField;

    private trizbortSettingsFontsLine lineField;

    '''<remarks/>
    public trizbortSettingsFontsRoom room { get; set; }
        {
            get
            {
            return Me.roomField;
        }
set(trizbortSettingsFontsRoom)
            Me.roomField = value;
        }
    }

    '''<remarks/>
    Public Property [object]() As trizbortSettingsFontsObject
        {
            get
            {
            return Me.objectField;
        }
set(trizbortSettingsFontsObject)
            Me.objectField = value;
        }
    }

    '''<remarks/>
    public trizbortSettingsFontsLine line { get; set; }
        {
            get
            {
            return Me.lineField;
        }
set(trizbortSettingsFontsLine)
            Me.lineField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsFontsRoom;

    private int sizeField;

    private bool sizeFieldSpecified;

    private string valueField;

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int size { get; set; }
        {
            get
            {
            return Me.sizeField;
        }
set(Integer)
            Me.sizeField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool sizeSpecified { get; set; }
        {
            get
            {
            return Me.sizeFieldSpecified;
        }
set(Boolean)
            Me.sizeFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _;
    public string Value { get; set; }
        {
            get
            {
            return Me.valueField;
        }
set(String)
            Me.valueField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsFontsObject;

    private int sizeField;

    private bool sizeFieldSpecified;

    private string valueField;

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int size { get; set; }
        {
            get
            {
            return Me.sizeField;
        }
set(Integer)
            Me.sizeField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool sizeSpecified { get; set; }
        {
            get
            {
            return Me.sizeFieldSpecified;
        }
set(Boolean)
            Me.sizeFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _;
    public string Value { get; set; }
        {
            get
            {
            return Me.valueField;
        }
set(String)
            Me.valueField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsFontsLine;

    private int sizeField;

    private bool sizeFieldSpecified;

    private string valueField;

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _;
    public int size { get; set; }
        {
            get
            {
            return Me.sizeField;
        }
set(Integer)
            Me.sizeField = Value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _;
    public bool sizeSpecified { get; set; }
        {
            get
            {
            return Me.sizeFieldSpecified;
        }
set(Boolean)
            Me.sizeFieldSpecified = value;
        }
    }

    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()> _;
    public string Value { get; set; }
        {
            get
            {
            return Me.valueField;
        }
set(String)
            Me.valueField = value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsGrid;

    private string snapToField;

    private string visibleField;

    private string showOriginField;

    private int sizeField;

    '''<remarks/>
    public string snapTo { get; set; }
        {
            get
            {
            return Me.snapToField;
        }
set(String)
            Me.snapToField = value;
        }
    }

    '''<remarks/>
    public string visible { get; set; }
        {
            get
            {
            return Me.visibleField;
        }
set(String)
            Me.visibleField = value;
        }
    }

    '''<remarks/>
    public string showOrigin { get; set; }
        {
            get
            {
            return Me.showOriginField;
        }
set(String)
            Me.showOriginField = value;
        }
    }

    '''<remarks/>
    public int size { get; set; }
        {
            get
            {
            return Me.sizeField;
        }
set(Integer)
            Me.sizeField = Value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsLines;

    private int widthField;

    private string handDrawnField;

    private int arrowSizeField;

    private int textOffsetField;

    '''<remarks/>
    public int width { get; set; }
        {
            get
            {
            return Me.widthField;
        }
set(Integer)
            Me.widthField = Value;
        }
    }

    '''<remarks/>
    public string handDrawn { get; set; }
        {
            get
            {
            return Me.handDrawnField;
        }
set(String)
            Me.handDrawnField = value;
        }
    }

    '''<remarks/>
    public int arrowSize { get; set; }
        {
            get
            {
            return Me.arrowSizeField;
        }
set(Integer)
            Me.arrowSizeField = Value;
        }
    }

    '''<remarks/>
    public int textOffset { get; set; }
        {
            get
            {
            return Me.textOffsetField;
        }
set(Integer)
            Me.textOffsetField = Value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsRooms;

    private int darknessStripeSizeField;

    private int objectListOffsetField;

    private int connectionStalkLengthField;

    '''<remarks/>
    public int darknessStripeSize { get; set; }
        {
            get
            {
            return Me.darknessStripeSizeField;
        }
set(Integer)
            Me.darknessStripeSizeField = Value;
        }
    }

    '''<remarks/>
    public int objectListOffset { get; set; }
        {
            get
            {
            return Me.objectListOffsetField;
        }
set(Integer)
            Me.objectListOffsetField = Value;
        }
    }

    '''<remarks/>
    public int connectionStalkLength { get; set; }
        {
            get
            {
            return Me.connectionStalkLengthField;
        }
set(Integer)
            Me.connectionStalkLengthField = Value;
        }
    }
}

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _;
 System.SerializableAttribute(), _;
 System.Diagnostics.DebuggerStepThroughAttribute(), _;
 System.ComponentModel.DesignerCategoryAttribute("code"), _;
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true)> _;
Partial Public Class trizbortSettingsUI;

    private int handleSizeField;

    private int snapToElementSizeField;

    '''<remarks/>
    public int handleSize { get; set; }
        {
            get
            {
            return Me.handleSizeField;
        }
set(Integer)
            Me.handleSizeField = Value;
        }
    }

    '''<remarks/>
    public int snapToElementSize { get; set; }
        {
            get
            {
            return Me.snapToElementSizeField;
        }
set(Integer)
            Me.snapToElementSizeField = Value;
        }
    }
}

}